spring.application.name=SpringBoot_Project_06-One-To-One

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/springonetoonedb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect (Optional for Hibernate 6+)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080
