# ===============================
# Application Name
spring.application.name=MVCProject_07-EmploeeManagement
# ===============================

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/springmvcemployeedb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Thymeleaf Configuration
# ===============================
spring.thymeleaf.cache=false

# ===============================
# Server Port (Optional)
# ===============================
server.port=8080
