# ===============================
# Application
# ===============================
spring.application.name=SpringBoot_Project_23-Redis

# ===============================
# MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/redisdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Cache
# ===============================
spring.cache.type=redis

# ===============================
# Server
# ===============================
server.port=8080
