spring.application.name=SpringBoot_Project_17-Actuator
# Application Name


# Server Port
server.port=8080

# Enable All Actuator Endpoints
management.endpoints.web.exposure.include=*

# Show Complete Health Details
management.endpoint.health.show-details=always

# Enable Info Endpoint
management.info.env.enabled=true

# Application Information
info.app.name=Spring Boot Actuator Demo
info.app.version=1.0
info.app.description=Demo Project for Spring Boot Actuator
info.app.developer=Rajbala
