# ===============================
# Application Configuration
# ===============================

spring.application.name=SpringBoot_Project_21-SecurityWithSwagger


# Server Port
server.port=8080



# ===============================
# MySQL Database Configuration
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/securityempdb

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ===============================
# JPA Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true



# ===============================
# Thymeleaf Configuration
# ===============================

spring.thymeleaf.cache=false



# ===============================
# Swagger Configuration
# ===============================

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/v3/api-docs
