#WARING BEFORE RUN THIS PROJECT create the a new repository in git hub and pest the repository link in Config server project in application.properties and  RUN THE ConfigServer project and then run this
http://localhost:8081/get-name


spring.application.name=MicroService_Project-11-ConfigClient

server.port=8081

spring.profiles.active=dev

spring.config.import=configserver:http://localhost:8080
